### ISSUE TITLE
Pressing back button from any account details goes to the list of Loan account rather than that account type.

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/web-self-service-app#116]
Pressing back button from details of any of the account goes back to the list of loan accounts. Eg: If you are viewing details of Savings account and when the back button is pressed it goes back to the list of Loan accounts rather than the list of savings account.
![back_button](https://user-images.githubusercontent.com/21126132/42459725-e8a8b406-83b9-11e8-88cb-36377c07c7ef.gif)

**Comment by Rupeshiya** [comment]
I would like to fix this @ankit01ojha , Can I ?

**Comment by ankit01ojha** [comment]
@Rupeshiya  yeah sure, go ahead.

**Comment by ankit01ojha** [comment]
@Rupeshiya , Since, there is no update from you. I am adding this issue as a GCI task.

**Comment by jonathanzhang53** [comment]
@ankit01ojha The back button directs back to the last link, which would be http://localhost:3000/#!/accounts. By default, the loan accounts list shows up.

The only way I see to fix this is to add a back button on the account details page which takes the user back to savings account list.

Would that be a good solution?

**Comment by ankit01ojha** [comment]
@jonathanzhang53 , I think that will work. Can you first send me a mock-up describing where you want to put the back button?

**Comment by jonathanzhang53** [comment]
@ankit01ojha Sure. I will take this as a GCI task after I get some stuff reviewed.

**Comment by jonathanzhang53** [comment]
> @jonathanzhang53 , I think that will work. Can you first send me a mock-up describing where you want to put the back button?

https://www.figma.com/proto/b9qlcf8mVMfh0FB2PDL7ugRQ/Mifos-Back-Button?node-id=1%3A4&viewport=329%2C304%2C0.417535&scaling=min-zoom

Here is a figma prototype. (You can see without an account)
Click the back button at the top left and then click on the first account that is there to see how the functionality would work.

**Comment by jonathanzhang53** [comment]
@ankit01ojha 
This is a GIF of the mockup:
![backbutton](https://user-images.githubusercontent.com/41968151/48857891-9b7ba000-ed7f-11e8-8f4a-561adcd2e0d6.gif)

Could I implement this?

**Comment by jonathanzhang53** [comment]
Actually, it would be a hassle to put it in the top toolbar because it's not included in <md-content>, instead, I think it would be better to put it right above the cards on the detail page.

**Comment by ankit01ojha** [comment]
@jonathanzhang53 , yeah it will be better to put the back button at the top left of the card. In this way, the basic design of the app will not be changed.

**Comment by jonathanzhang53** [comment]
@ankit01ojha I was able to put the back button in but I am unable to reroute to the account list while making the savings tab active. I left a comment on the GCI task about what I had in mind but I'm not sure how to execute it.

**Comment by ankit01ojha** [comment]
@jonathanzhang53 , what can be done here is that you can use is ```md-selected``` and set it to a variable for the tab index. You can save the index of the tab in the sessionStorage and change the value of the variable as per the tabIndex. Once, an account detail is clicked the index of the tab will be stored in the cache and when the user comes back to account list page you can retrieve the tab index from the cache and then set the value for the ```md-selected```.
![tabs-back](https://user-images.githubusercontent.com/21126132/48946770-acb2e100-ef26-11e8-8ee7-ed30360fa4cd.gif)
