### ISSUE TITLE
 Filled every info correctly but unable to signup.

### ISSUE THREAD

**Issue by Rupeshiya** [openMF/web-self-service-app#129]
### Screenshot indicates about the issue   
![screenshot 35](https://user-images.githubusercontent.com/31209617/46569335-e036ad80-c970-11e8-9410-3481bbdd549a.png)

 please give your review

**Comment by Rupeshiya** [comment]
@botraunak  give your review please.

**Comment by ankit01ojha** [comment]
@Rupeshiya This feature is available in the develop branch only( for now). And you should be a self-service client for registering to the app. You can refer the GIF here ( point no. 2 ) https://gist.github.com/ankit01ojha/fe46be98bf69883c37e4497ca4f1e076

**Comment by Rupeshiya** [comment]
@ankit01ojha  Then How can I check issue #118  #116  locally without login ?

**Comment by ankit01ojha** [comment]
@Rupeshiya for login use these credentials ``` username: selfservice ```  and ```password: password```.

**Comment by Rupeshiya** [comment]
thanks @ankit01ojha

**Comment by joeedwin** [comment]
you should close this issue @Rupeshiya
