### ISSUE TITLE
Refreshing the page changes the language back to English

### ISSUE THREAD

**Issue by ankit01ojha** [openMF/web-self-service-app#137]
When language is changed from English  ( Eg: Hindi ) and when the page is refreshed the language gets changed back to English.

**Comment by jonathanzhang53** [comment]
@ankit01ojha how do I change the language?

**Comment by jonathanzhang53** [comment]
Hi, I found a solution either using local storage or cookie storage. Which would be preferred? @ankit01ojha

**Comment by jonathanzhang53** [comment]
I think I will use local storage. It can be changed with one line to cookie storage if needed. I will submit PR now.
