### ISSUE TITLE
Opening the logout menu throws deprecation warning.

### ISSUE THREAD

**Issue by aashish-ak** [openMF/web-self-service-app#149]
## Description
On clicking the logout menu button, the browser throws an error in the browser console `mdMenu: The $mdOpenMenu method is deprecated. Please use $mdMenu.open.`
## Steps to reproduce
Click on the logout menu button and open the browser console , you can see the deprecation warning there.
## Cause of error
In file `main.html`, the method `$mdOpenMenu()` is being used which is now deprecated, so it should be changed to `$mdMenu.open()`, to remove the warning.
## Settings:
    -Browser used: Google Chrome
    -Operating System: Ubuntu Xenial 16.04
# Screenshots/GIFs, if any:
![profile](https://user-images.githubusercontent.com/21988675/50994938-977c2b00-1543-11e9-9410-5b6e180cc9de.png)

**Comment by Rupeshiya** [comment]
@aashish-ak  are you working on this ?
