### ISSUE TITLE
Cannot log into Self-service User

### ISSUE THREAD

**Issue by francisguchie** [openMF/web-self-service-app#180]
##Description
A self service user can not log into the the web-self-service-app

##Steps to reproduce
Follow the steps in the [READ ME](https://github.com/openMF/web-self-service-app#readme) - run gulp serve to start the server

##Expected Behaviour
A Self service user (client in this case) should be able to log in 

##Actual Behaviour
Instead an error 
{"timestamp":1632438329760,"status":400,"error":"Bad Request","message":"","path":"/fineract-provider/api/v1/self/authentication"}

##Settings:
    -Browser used: Mozilla FireFox, Microsoft Edge & Chrome
  
##Screenshots/GIFs, if any:
Please attach screenshots/GIFs of the error/issue.

**Comment by francisguchie** [comment]
This is where the challenge is 
login in information is not passed on as a json body 
/fineract-provider/api/v1/self/authentication?password=password&username=mifos

following this [FINERACT-726](https://issues.apache.org/jira/browse/FINERACT-726) this was changed and i think we should address this too

**Comment by ikimbra** [comment]
True. 
The login is only available for the super user but not the client.

**Comment by francisguchie** [comment]
@rrpawar @Blasan, have you looked at this

**Comment by francisguchie** [comment]
@rrpawar96 Have you looked at 

This is where the challenge is
login in information is not passed on as a json body
/fineract-provider/api/v1/self/authentication?password=password&username=mifos

following this FINERACT-726 this was changed and i think we should address this too

**Comment by francisguchie** [comment]
@Blasan @ikimbra  
thanks to @rrpawar96 there is a PR solving the login to the latest build of fineract i.e. the login request coming in as json file as suggested in  https://issues.apache.org/jira/browse/FINERACT-726

**Comment by francisguchie** [comment]
@Blasan  @luckyman20 @rrpawar96 
More changes and now no API errors after clicking log in nothing changes on the screen

https://user-images.githubusercontent.com/22683654/135938903-a8dcb132-970b-4099-8425-6194a1ceae0a.mp4

**Comment by francisguchie** [comment]
@ikimbra  have you tested this ?

**Comment by francisguchie** [comment]
@rrpawar96 after trying out 2 browsers on the same PC , I finally see the dashboard and I can see data on in the browser. This is confusing. The web-self-service-app seems to have its own brain

**Comment by pete10200** [comment]
Was this issue resolved anyhow? Are there any tricks that can be implemented meanwhile?
 
{"timestamp":1641671332070,"status":400,"error":"Bad Request","message":"","path":"/fineract-provider/api/v1/self/authentication"}

**Comment by francisguchie** [comment]
@pete10200  it was solved - it was something connected to a number of changes in Apache Fineract. 
@rrpawar96 helped me resolve it - may be let him make a PR for it

**Comment by pete10200** [comment]
Thanks

**Comment by rrpawar96** [comment]
Hi @francisguchie @pete10200 PR is already been created for this issue ; https://github.com/openMF/web-self-service-app/pull/182

**Comment by rrpawar96** [comment]
Please test this PR https://github.com/openMF/web-self-service-app/pull/182 let me know @pete10200 if this PR also doesn't help you, I will create new PR then

**Comment by francisguchie** [comment]
@pete10200  should test, me i tested long time ago and it works just fine. May be some one should merge

**Comment by pete10200** [comment]
@rrpawar96 @francisguchie   sorry i think my issue is a bit lost. this solution is for web-self-service-app i am looking for a solution for the self service android mobile up where the same problem is encountered.

{"timestamp":1641671332070,"status":400,"error":"Bad Request","message":"","path":"/fineract-provider/api/v1/self/authentication"}

**Comment by rrpawar96** [comment]
@pete10200 can you paste the link of that repository will be easy to help you then

**Comment by pete10200** [comment]
gh repo clone openMF/mifos-mobile

https://github.com/openMF/mifos-mobile

**Comment by rrpawar96** [comment]
Please create a issue in that repository, I will paste some code in that issue @pete10200

**Comment by pete10200** [comment]
@rrpawar96 have created issue "Bad Request","message":"","path":"/fineract-provider/api/v1/self/authentication"} #1825

**Comment by pete10200** [comment]
> Please test this PR #182 let me know @pete10200 if this PR also doesn't help you, I will create new PR then

@rrpawar96 I have tested this and it works fine also applying PR #183 gives a fine resolution to the problems. Thanks.

**Comment by salissou-msc** [comment]
Hi, I have this issu of authentication, send the link to download the fixed software.

Thanks

**Comment by salissou-msc** [comment]
Dears,

I have authentication issue on my Mifos local server with android client. Can you please send the link to download the patch ?

Thanks//

**Comment by francisguchie** [comment]
Issue was solved
