### ISSUE TITLE
Add Login error handler

### ISSUE THREAD

**Issue by botraunak** [openMF/web-self-service-app#52]
When authentication fails, on the login the UI goes into a loading state.
It should reset and show a notification for wrong credentials

Replicate by trying to login with 
username: selfservice 
password: anything

Works fine when you login with right credentials

Screenshot
<img width="1680" alt="screen shot 2017-10-25 at 9 01 25 am" src="https://user-images.githubusercontent.com/7816559/31979217-1ddb8bc0-b963-11e7-888c-6c903d5cb819.png">

**Comment by ankit01ojha** [comment]
I would like to work on this.

**Comment by botraunak** [comment]
@ankit01ojha Sure go ahead!
