### ISSUE TITLE
Cancel Button does not work at various places

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-self-service-app#68]
The cancel button does nothing when clicked. This bug is present in the transfers, third-party transfers and the apply for loan section.

**Comment by abhaychawla** [comment]
I want to take up this issue. @botraunak I want to know your opinion, whether the user should be redirected to dashboard on pressing the cancel button or just the textfields should go blank.

**Comment by botraunak** [comment]
@abhaychawla just clear all the fields!

**Comment by abhaychawla** [comment]
Okay! Working on this.

**Comment by abhaychawla** [comment]
@botraunak I am unable to login with the credentials provided in the wiki page. Have they been changed?

**Comment by sarthak-sehgal** [comment]
@botraunak, I'm facing the same issue. Have the login credentials been changed?

**Comment by botraunak** [comment]
@abhaychawla  @sarthak-sehgal, yes it's not working for me as well, let me change the password on the demo instance and update the wiki

**Comment by botraunak** [comment]
Find the new credentials updated on the wiki page [here](https://github.com/openMF/web-self-service-app/wiki)

**Comment by abhaychawla** [comment]
Okay! thanks

**Comment by abhaychawla** [comment]
@botraunak While working on the issue I found out that the code seems to consist of 2 copies of files for the transfers section.
In app/src/tpt --> transfers.html, transfers.component.js, transfers.service.js
and in app/src/transfers --> transfers.html, transfers.component.js, transfers.service.js
Same is the case for the review-transfer-dialog

The issue is that the template is being taken from the transfers folder while the controller is being picked up from the tpt folder (as both controllers have been declared with the same name it creates ambiguity).

I guess one of the sets of files was supposed to be removed but there seems to be a little difference in them, so I wanted to ask you that which one is supposed to be kept and which one removed?

**Comment by botraunak** [comment]
@abhaychawla Good catch, the `transfer.component` files should not belong there and should be removed. Can you open a separate issue for this? you can come back to this issue later.

**Comment by abhaychawla** [comment]
Sure!
