### ISSUE TITLE
gulp forever

### ISSUE THREAD

**Issue by nicomoscoloni** [openMF/web-self-service-app#71]
Hi Guys, how I can run the command "gulp server" for forever?
When I close the ssh terminal the app turn off.
Any solutions? thanks

**Comment by NirmalKumarJoshi** [comment]
Try this:

forever start -c "gulp" serve

The -c option allows you to use any command.

**Comment by botraunak** [comment]
@ciarg You should really not be using the gulp serve on the production server, the `gulp serve` command is only for local development, what you should do in the ideal case is run `gulp build` and then serve the dist directory through a server like `nginx` or `apache`
