### ISSUE TITLE
Gulp serve

### ISSUE THREAD

**Issue by GS3207** [openMF/web-self-service-app#74]
TypeError: require.extensions.hasOwnProperty is not a function
This is the error that appears when Gulp serve is executed. It is an issue with require-dir and nodejs 8.
Did not find a fix yet.

**Comment by abhaychawla** [comment]
@GS3207 I guess you are working on the wrong branch of the repository. The latest code is being maintained on the develop branch where this isn't an issue.

**Comment by botraunak** [comment]
@abhaychawla thank you for the providing the clarification!

@GS3207 The default branch for contributions is `develop` Please switch to that branch for development 👍
