### ISSUE TITLE
Redundant files in tpt directory

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-self-service-app#75]
The code consists of two copies of the same set of files for the transfers section in the following directories:
- app/src/tpt --> transfers.html, transfers.component.js, transfers.service.js
- app/src/transfers --> transfers.html, transfers.component.js, transfers.service.js
Same is the case for the review-transfer-dialog.

The redundant files do not belong to the tpt directory and should be removed.

**Comment by abhaychawla** [comment]
Working on the issue.

**Comment by botraunak** [comment]
@abhaychawla Also remove the duplicate `review-transfer-dialog` in the `tpt` directory!

**Comment by abhaychawla** [comment]
Done!

**Comment by botraunak** [comment]
Ref: #76
