### ISSUE TITLE
Create a template for Issues and Pull Requests for the repository

### ISSUE THREAD

**Issue by abhaychawla** [openMF/web-self-service-app#80]
Adding a template for issues and pull requests will help the contributors share all the required important information which will be helpful to the community as a whole. (Similar templates can be implemented here as in the community app of mifos)

**Comment by abhaychawla** [comment]
@botraunak Can I work on this?

**Comment by aashish-ak** [comment]
@botraunak @santoshconflux Can i work on this?

**Comment by ankit01ojha** [comment]
@aashish-ak , it is done already #110
