### ISSUE TITLE
Responsiveness enhancement

### ISSUE THREAD

**Issue by anweshknayak** [openMF/web-self-service-app#84]
![selfserv](https://user-images.githubusercontent.com/8139783/36603836-0ebcba68-18e2-11e8-975e-bdf0d86d219b.gif)

It should be vertical scrollable if UI needs to be enhanced for mobile view

**Comment by pratyush1687** [comment]
hi, i think this issue is same as #77

**Comment by anweshknayak** [comment]
@pratyush1687 I think there are more components to enhance than only cards.

**Comment by botraunak** [comment]
#77
